### PR TITLE
Fix new android and refactor

### PR DESCRIPTION
**Pull request by david-serrano**

### CODE REVIEW

**Review by Spikeysanju — APPROVED** [review]
It LGTM!... PR Approved 👍

**Comment by david-serrano** [comment]
i think you have to be the one to merge 😄

**Comment by Spikeysanju** [comment]
Sorry man, I was reviewing your PR from mobile. I thought to recheck everything once I reach the home. That's the reason for the hold. Anyway PR is approved. Merging rn 👍

**Comment by Spikeysanju** [comment]
PR Merged 🚀

**Pull request merged**
